name: Lint
on: push
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with:
            node-version: 16
      - name: Install dependencies
        run: yarn install
      - name: Build contracts
        run: yarn run build
      - name: Run lint
        run: yarn run lint
